language: python

python:
  - 3.5.3

services: postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

env:
  global:
    - PGPORT=5432
    - DJANGO=2.0.4
  
  
before_install:
  - export DJANGO_SETTINGS_MODULE=lyricloud/settings.py
  - export PYTHONPATH=$HOME/builds/jonah-potter/lyricloud
  - export PIP_USE_MIRRORS=true

install:
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE lyricloud;" -U postgres

script:
  - python manage.py migrate

notifications:
  slack: eureka-house:2nhj72jN7vB07HpBZmU0s396