language: python

python:
  - 3.5.3

services: postgresql

env:
  - DJANGO=2.0.4

before_install:
  - export DJANGO_SETTINGS_MODULE=settings.py
  - export PYTHONPATH=$HOME/builds/jonah-potter/lyricloud
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE lyricloud;" -U postgres

script:
  - python manage.py syncdb --noinput