# Generated by Django 2.0.4 on 2018-04-14 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('credit', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SongWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.Song')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='songword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.Word'),
        ),
        migrations.AddField(
            model_name='song',
            name='words',
            field=models.ManyToManyField(through='cloud.SongWord', to='cloud.Word'),
        ),
    ]
